version: '2'

services:
  pg:
    build:
      context: ./sqitch
      dockerfile: Dockerfile.pg
    environment:
      - POSTGRES_PASSWORD=password
  api:
    build: .
    volumes:
      - .:/opt/api
    working_dir: /opt/api
    environment:
      PG_USER: 'postgres'
      PG_PASSWORD: 'password'
      PG_PORT: 5432
      PG_HOST: 'pg'
      PG_DATABASE: 'postgres'
      HASHID_SALT: 'freakyunsecuresalt'
    ports:
      - "9000:8080"
    command: bash -c "stack build --allow-different-user --exec \"stack exec sr-exe --allow-different-user\""
  proxy:
    image: mitmproxy/mitmproxy
    volumes:
      - ./utils/proxy:/opt/proxy
    working_dir: /opt/proxy
    command: mitmproxy -R http://api:8080/
    ports:
      - "8080:8080"
